[env]
TERM = "xterm-256color"

[window]
padding = { x = 4, y = 4 }

decorations = "None"
opacity = 0.875

startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMonoNL NFM" }
size = 14

[colors]
primary = { background = "#191724" }
